//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel inträffades vid tilläggning av kontakt..
        /// </summary>
        internal static string AddContactError {
            get {
                return ResourceManager.GetString("AddContactError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ledsen - kontakten du söker finns inte eller har blivit borttagen..
        /// </summary>
        internal static string ContactNotFoundError {
            get {
                return ResourceManager.GetString("ContactNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel inträffades vid borttagning av kontakt..
        /// </summary>
        internal static string DeleteContactError {
            get {
                return ResourceManager.GetString("DeleteContactError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}) togs bort..
        /// </summary>
        internal static string DeleteContactSuccess {
            get {
                return ResourceManager.GetString("DeleteContactSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel inträffades vid hämtning av alla kontakter..
        /// </summary>
        internal static string GetAllContactsError {
            get {
                return ResourceManager.GetString("GetAllContactsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel inträffades vid hämtning av kontakt..
        /// </summary>
        internal static string GetContactError {
            get {
                return ResourceManager.GetString("GetContactError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel inträffades vid hämtning av sista {0} kontakterna..
        /// </summary>
        internal static string GetContactsWithOffsetError {
            get {
                return ResourceManager.GetString("GetContactsWithOffsetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel inträffades vid sparning av kontaktlistan..
        /// </summary>
        internal static string SaveContactsError {
            get {
                return ResourceManager.GetString("SaveContactsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett oväntat fel inträffades..
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel inträffades vid uppdatering av kontakt..
        /// </summary>
        internal static string UpdateContactError {
            get {
                return ResourceManager.GetString("UpdateContactError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}) blev uppdaterad..
        /// </summary>
        internal static string UpdateContactSuccess {
            get {
                return ResourceManager.GetString("UpdateContactSuccess", resourceCulture);
            }
        }
    }
}
